# -*- coding: utf-8 -*-
"""Logistic Regression Spam Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_2g2AQQUR9wQxdW0aPrjZoh8fnCHq-Qo
"""



from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/spam.csv', encoding='latin-1')
df = df[['v1', 'v2']]
df.columns = ['label', 'message']

df['label'] = df['label'].map({'ham': 0, 'spam': 1})

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

X_train, X_test, y_train, y_test = train_test_split(df['message'], df['label'], test_size=0.2, random_state=42)

vectorizer = TfidfVectorizer(stop_words='english')
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

model = LogisticRegression(class_weight='balanced')
model.fit(X_train_vec, y_train)

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

y_pred = model.predict(X_train_vec)

print('Accuracy:', accuracy_score(y_train, y_pred))
print('Classification Report:\n', classification_report(y_train, y_pred))
print('Confusion Matrix:\n', confusion_matrix(y_train, y_pred))

check_spam = "Take our quick survey and earn a $50 gift card! Limited time offer, click to participate: [Link Spam]"

check_spam_vec = vectorizer.transform([check_spam])
prediction = model.predict(check_spam_vec)

prediction_label = 'Spam' if prediction[0] == 1 else 'Bukan Spam'
print(f'SMS : {check_spam}\n{prediction_label}')

